[package]
name = "cli_tool"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.10"
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
	
